"""Initial tables

Revision ID: 5e937253a163
Revises: 
Create Date: 2024-09-12 16:42:24.800985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e937253a163'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_requests',
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('load_date', sa.DateTime(), nullable=False),
    sa.Column('delivery_city', sa.String(), nullable=False),
    sa.Column('delivery_address', sa.String(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('delivery_time', sa.Time(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('package_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('internal_id')
    )
    op.create_index(op.f('ix_delivery_requests_internal_id'), 'delivery_requests', ['internal_id'], unique=False)
    op.create_table('delivery_status_current',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.Column('load_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['internal_id'], ['delivery_requests.internal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_status_current_id'), 'delivery_status_current', ['id'], unique=False)
    op.create_table('delivery_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.Column('load_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['internal_id'], ['delivery_requests.internal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_status_history_id'), 'delivery_status_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_status_history_id'), table_name='delivery_status_history')
    op.drop_table('delivery_status_history')
    op.drop_index(op.f('ix_delivery_status_current_id'), table_name='delivery_status_current')
    op.drop_table('delivery_status_current')
    op.drop_index(op.f('ix_delivery_requests_internal_id'), table_name='delivery_requests')
    op.drop_table('delivery_requests')
    # ### end Alembic commands ###
