"""add warehouses table

Revision ID: d23126ef7a4c
Revises: 6d709febad71
Create Date: 2024-09-13 11:08:17.873882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23126ef7a4c'
down_revision: Union[str, None] = '6d709febad71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wh_city', sa.String(), nullable=False),
    sa.Column('wh_address', sa.String(), nullable=False),
    sa.Column('wh_lat', sa.Float(), nullable=False),
    sa.Column('wh_lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wh_city', 'wh_address', name='uq_city_address')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.drop_constraint('delivery_status_current_internal_id_fkey', 'delivery_status_current', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_status_current', 'delivery_requests', ['internal_id'], ['internal_id'], ondelete='CASCADE')
    op.drop_constraint('delivery_status_history_internal_id_fkey', 'delivery_status_history', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_status_history', 'delivery_requests', ['internal_id'], ['internal_id'], ondelete='CASCADE')

    # Вставка дополнительных данных - адреса складов
    op.execute("""
            INSERT INTO warehouses (wh_city, wh_address, wh_lat, wh_lon) VALUES
            ('Казань', 'ул. Островского, 98', 55.77934, 49.132362),
            ('Набережные Челны', 'пр-т. Московский, 161', 55.7445032, 52.4310476),
            ('Нижнекамск', 'сквер Лемаева, 2', 55.6375266, 51.8179653),
            ('Альметьевск', 'ул. Ленина, 100', 54.8994779, 52.2740343),
            ('Зеленодольск', 'ул. Королева, 1', 55.8535239, 48.5648484)
            ON CONFLICT (wh_city, wh_address) DO NOTHING;
            """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_status_history', type_='foreignkey')
    op.create_foreign_key('delivery_status_history_internal_id_fkey', 'delivery_status_history', 'delivery_requests', ['internal_id'], ['internal_id'])
    op.drop_constraint(None, 'delivery_status_current', type_='foreignkey')
    op.create_foreign_key('delivery_status_current_internal_id_fkey', 'delivery_status_current', 'delivery_requests', ['internal_id'], ['internal_id'])
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
